# Base URL to use when resolving relative URLs in local files
base_url = "/workspaces/fsdh-pfds-docs/docs"

# Output format
format = "compact"

# Fallback extensions to apply when a URL does not specify one
fallback_extensions = ["md", "mdx"]

# URLs or patterns to exclude (supports regex)
exclude = [
    "file:///",
    '\.(pdf|zip|png|jpg)$',
    "sharepoint.com"
]

# verbose = "info"

# Proceed even if the server connection is considered insecure (invalid TLS)
insecure = true

# List of accepted status codes for valid links
accept = [200]