
name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 26
          cache: npm

      - name: Install Deps
        run: npm ci

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > docs/.vuepress/dist/.nojekyll

      - name: Add CNAME for GitHub Pages
        run: echo "documentation.sds.canada.ca" > ./docs/.vuepress/dist/CNAME

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: docs/.vuepress/dist

      - name: Post deployment message
        run: echo "Documentation deployed to GitHub Pages"
