---
name: Secret scanning

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  pr-secret-scan:
    name: Secret scan PR changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@363923b901c911a9164f50b6c423f47c15372b1c # v3.97.4
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --results=verified,unknown
