name: Update to the Terms and Conditions

on:
  push:
    branches: [ main ]
    paths:
      - docs/en/Terms-And-Conditions.md
      - docs/fr/Conditions-generales.md

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Make tag name
        id: mk
        run: |
          TAG="$(date -u +%Y.%m.%d)"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          tag_name: ${{ steps.mk.outputs.tag }}
          name: FSDH Terms & Conditions - Updated ${{ steps.mk.outputs.tag }}
          body: |
            Automated release triggered by file changes in commit ${{ github.sha }}.

            **Commit message:** ${{ github.event.head_commit.message }}
          files: |
            docs/en/Terms-And-Conditions.md
            docs/fr/Conditions-generales.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  update-last-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Create App token
        id: create_token
        uses: ssc-sp/.github/.github/actions/create-app-token@main
        with:
          app-id: ${{ vars.TERMS_CONDITIONS_NOTARY_ID }}
          private-key: ${{ secrets.TERMS_CONDITIONS_NOTARY_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ steps.create_token.outputs.token }}

      - name: Update LAST_UPDATED.md
        run: |
          echo "$(date -u +'%Y-%m-%d')" > LAST_UPDATED.md

      - name: Commit and push updated JSON
        shell: bash
        run: |
          set -euo pipefail

          git config user.name "Terms and Conditions App"
          git config user.email "${{ vars.TERMS_CONDITIONS_NOTARY_ID }}[bot]@users.noreply.github.com"

          git add LAST_UPDATED.md
          git commit -m "Update LAST_UPDATED.md to date of release"

          git push